// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGWg5NeNnE59xZt2FVZg1JpuDQz-L97rA',
    appId: '1:816293070735:web:ec7b85de082d59e9e3adfa',
    messagingSenderId: '816293070735',
    projectId: 'whatsappweb-a4185',
    authDomain: 'whatsappweb-a4185.firebaseapp.com',
    storageBucket: 'whatsappweb-a4185.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH7xdoio1yxpVk_jQxDEwCimzzNmK4Z9w',
    appId: '1:816293070735:android:d5874adc9a2665b7e3adfa',
    messagingSenderId: '816293070735',
    projectId: 'whatsappweb-a4185',
    storageBucket: 'whatsappweb-a4185.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1_UEPW1HYapnB6hv6Gkvd9iP2N5CCrmo',
    appId: '1:816293070735:ios:93d96750951a127ee3adfa',
    messagingSenderId: '816293070735',
    projectId: 'whatsappweb-a4185',
    storageBucket: 'whatsappweb-a4185.appspot.com',
    iosBundleId: 'com.nfdeveloper.watsappweb',
  );
}
